### ISSUE TITLE
PreprocessReads return non-zero exit status -11

### ISSUE THREAD

**Issue by dingquanyu** [gdiminin/HaSAPPy#9] opened 2021-01-06 09:35 UTC
Hello. I was running LoadModule_test_from_Trim.txt but the subprocess PreprocessReads reported a non-zero exit -11:
subprocess.CalledProcessError: Command 'PreprocessReads -i /HaSAPPy/docs/test/Sequence.fastq -o /HaSAPPy/test_data/experiments/test/test_1_2021-01-06/raw/test_1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f' returned non-zero exit status -11

**Comment by gdiminin** [comment] 2021-01-06 12:33
Hi. Can you run the command (PreprocessReads -i /HaSAPPy/docs/test/Sequence.fastq -o /HaSAPPy/test_data/experiments/test/test_1_2021-01-06/raw/test_1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f) directly on the terminal so that we can have more informations on the problem

**Comment by dingquanyu** [comment] 2021-01-06 12:45
Thanks and here's the error:
Error out of memory at line 294 in file PreprocessReads.cu
Setting parameters:
	Input file name  :/HaSAPPy/docs/test/Sequence.fastq
	Output file name : /HaSAPPy/test_data/experiments/test/test_1_2021-01-05/raw/test_1_QS.fastq
	Adaptor sequence : ATCTCGTATGCCGTCTTCTGCTT

5 CUDA devices with at least compute capability 3.5 and 6 GB memory found.

I got this error while running with 6GB memory then I tried again with 10 GB memory but still got the same error. I checked the size of the Sequence.fastq which is just 64 MB. I have no idea why it reported out of memory in both cases.

**Comment by dingquanyu** [comment] 2021-01-06 13:15
Thanks and here's the error:


Error out of memory at line 294 in file PreprocessReads.cu
Setting parameters:
Input file name :/HaSAPPy/docs/test/Sequence.fastq
Output file name : /HaSAPPy/test_data/experiments/test/test_1_2021-01-05/raw/test_1_QS.fastq
Adaptor sequence : ATCTCGTATGCCGTCTTCTGCTT

5 CUDA devices with at least compute capability 3.5 and 6 GB memory found.

I got this error while running with 6GB memory then I tried again with 10 GB memory but still got the same error. I checked the size of the Sequence.fastq which is just 64 MB. I have no idea why it reported out of memory in both cases.

May I also check with you about another question while running HaSAPPy, please? In some cases, the number of KI in control is 0 while that in selected cells are high. How would you calculate KI_fold in this case as no number should be divided by 0?  Many Thanks.

**Comment by gdiminin** [comment] 2021-01-06 14:18
1)KI_fold. if the n of insertions in the control are =0 and in the selected >0, just for the fold calculation the denominator(control KI) is =1 to allow the division.
2)PreprocesseReads. Can you remove the pre-compiled PreprocessReads available in HaSAPPy(../HaSAPPy/HaSAPPy/PreprocessReads) and re-compiled it from https://github.com/zanton123/PreprocessReads ? Let me know if the instructions are not clear enough

**Comment by dingquanyu** [comment] 2021-01-06 14:25
Thanks a lot. I’ll try that and rerun it. 

Can I also double-check with you about the concept of _no_feature generated by HaSAPPy? Does that mean any sequence that fail to be assigned to an already-known gene with a gene name?

**Comment by dingquanyu** [comment] 2021-01-06 15:19
Hello, unfortunately the same error occurred again even after I remove the original PreprocessReads and compiled the one from zanton123: 

Error out of memory at line 294 in file PreprocessReads.cu
Setting parameters:
Input file name :/HaSAPPy/docs/test/Sequence.fastq
Output file name : /HaSAPPy/test_data/experiments/test/test_1_2021-01-05/raw/test_1_QS.fastq
Adaptor sequence : ATCTCGTATGCCGTCTTCTGCTT

5 CUDA devices with at least compute capability 3.5 and 6 GB memory found.

**Comment by gdiminin** [comment] 2021-01-06 19:49
It is possible that the issue depends the fact that PreprocessReads.cu has be designed to work with 2 GPUs. Can you try on the command line to run this command where you specify to use just 2 GPUs:
PreprocessReads -i /HaSAPPy/docs/test/Sequence.fastq -o /HaSAPPy/test_data/experiments/test/test_1_2021-01-06/raw/test_1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f -Dev 0 -Dev 1

If this is going to fix the problem I will introduce the change in HaSAPPy.

Yes _no_feature represents regions not assigned to any known gene

**Comment by dingquanyu** [comment] 2021-01-06 20:13
Thanks for the advice. Unfortunately, it reported OUT_OF_MEMORY error again while I was using 2 gpu with 10gb memory by specifying #SBATCH --gres=gpu:2 #SBATCH --mem=10gb: 
/var/spool/slurm/job9984255/slurm_script: line 13: 11861 Killed                  PreprocessReads -i /HaSAPPy/docs/test/Sequence.fastq -o /HaSAPPy/test_data/experiments/test/test_1_2021-01-05/raw/test_1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f -Dev 0 -Dev 1
slurmstepd: error: Detected 1 oom-kill event(s) in step 9984255.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by gdiminin** [comment] 2021-01-06 20:26
It is necessary to modify the PreprocessReads program. Zanton123 will help to fix these bugs but some feedback will be necessary because he will not be able to test the program for more than 4 GPUs (for hardware constrains).

**Comment by dingquanyu** [comment] 2021-01-06 20:32
Thanks a lot. Meanwhile do you think it’s worth re-compiling the PreprocessReads from HaSAPPy’s build and running with 2 gpus or that PreprocessReads is the sam as Zanton123’s?

**Comment by gdiminin** [comment] 2021-01-07 06:51
it is a newer version. I don't think is going to make the difference...but why not trying. I'm surprised that specifying the GPUs is not sufficient to bypass the bug. It would be great if you can test for us the new version of PreprocessReads when it will be modified.

**Comment by gdiminin** [comment] 2021-01-07 11:08
I send the comment of Zanton123:
"I did correct the out of bounds and have made new builds and wonder if one of the new builds (in the PreprocessReads/builds folder of the github repository) would work (attached a cuda 6.5 min, and an instrumented cuda 7.5 binary). I could reproduce the earlier error with 4 GPUs and the new version fixes this error.
 
The commit:
https://github.com/zanton123/PreprocessReads/commit/74c54c895ae50ee4381958fc822b4c0f98a9d0b4
 
The new error it looks like there might potentially be a different issue from the server or batch system. On a server or cloud would certainly be more complex and we would need to take more into consideration. All I can see is the error has been issued by the OS and does not come form code that I can control - the latter certainly caused it but the reason seems resource limits (memory) allocated from the batch system. 3 things:
 
I wonder if simply 2 GPUs with each 6GB have exceeded the 10GB limit. To reduce the memory footprint using only -Dev 0 could help.
 
I also start to wonder now if there could be a confusion with the --mem=10gb  not really about GPU memory but CPU memory. The code makes a number of pinned allocations for buffers to and from the GPU and has no concerns about CPU memory limitations. In case --mem=10gb is only 10GB CPU memory increasing would be advisable. 
 
I would not really know off head if additional considerations are needed if Nvidias GPU virtualization or nvDocker were used. Could you kindly ask what type of system this is supposed to run on (minimally we would need to know the Linux and Nvidia driver version, and possibly the machine architecture eg DGX-1 and if GPU virtualization is enabled on the system). This would allow me to look into the relevant APIs and maybe find how to possibly debug this on the client machine."

**Comment by dingquanyu** [comment] 2021-01-09 14:20
Hi thanks a lot for sending the comments and I tried the advice but no progress so far. I’m now wondering if it’s because there’re errors while I compiled ngm and nvbio (make error 2  i.e. I didn’t actually install the two programmes on the cluster), the memory exceeds the limit? I did successfully installed bowtie2 and add to PATH, though.

**Comment by dingquanyu** [comment] 2021-01-09 15:56
Hello, 

Good evening. Many apologies but I finally managed to solve all those issues by switching to another workstation. Now HaSAPPy can run successfully. Thanks for your comments and advice. May I also ask if you plan to migrate the programme to python3 platform as python2.7 may not be supported soon? Thanks.

**Comment by gdiminin** [comment] 2021-01-11 08:24
I'm glad that you succeeded to fix the issue. We are still using the software and we are working on the migration to python3.
If you need any additional support please let me know.

**Closed as completed by gdiminin** 2021-01-11 08:24 UTC

**Comment by HenryWotton** [comment] 2021-01-11 10:39
> I'm glad that you succeeded to fix the issue. We are still using the software and we are working on the migration to python3.
> If you need any additional support please let me know.

That's very good to know! Sorry another question is that while editing section 0F, if "N" is put in whether section 7 will be run, there'll be an error raised. The error will be resolved by substituting N with Y even though in some cases I don't want to run group comparisons. Maybe you could update the code to tolerate the input "N" in section 0F?

In addition, may I please ask how you set up section 7 while analysing the haploid screening on LASV entry data from Jae et al, 2013? Specifically section 7A - 7E. Many thanks.

**Comment by HenryWotton** [comment] 2021-01-11 10:39
That's very good to know! Sorry another question is that while editing section 0F, if "N" is put in whether section 7 will be run, there'll be an error raised. The error will be resolved by substituting N with Y even though in some cases I don't want to run group comparisons. Maybe you could update the code to tolerate the input "N" in section 0F?

In addition, may I please ask how you set up section 7 while analysing the haploid screening on LASV entry data from Jae et al, 2013? Specifically section 7A - 7E. Many thanks.
